### ISSUE TITLE
Pass in MasterFile as an interface to DnsServer

### ISSUE THREAD

**Issue by greggman** [kapetan/dns#12]
I needed a far more dynamic answer for my DNS server so I modified the code so that DnsServer takes a `IQuestionAnswerer` (horrible name - suggest a new one). `MasterFile` is then an implementor of `IQuestionAnswerer`.

https://github.com/kapetan/dns/compare/master...greggman:q-and-a

This has a few advantages
1. I can pass in other implementations of `IQuestionAnswerer`.
2. No need for an getter for `MasterFile` on `DnsServer`. 
3. I guess a corollary of 1 is more ways to unit test DnsServer since you could pass in a mock

Any interest in this? Should I turn it into a PR?

**Comment by kapetan** [comment]
The `DnsServer` now accepts an `IRequestResolver` in the constructor, and `MasterFile` implements the interface.
