### ISSUE TITLE
Support no-arg constructor on DnsServer

### ISSUE THREAD

**Issue by richardgavel** [kapetan/dns#25]
I'm writing a custom DNS server that will resolve host-running Docker containers. This DNS server will be added to the list of DNS servers. There is no need for the endpoint server because if I can't resolve the request, I don't want to forward it on, I want the next DNS server configured to try and resolve it.

**Comment by kapetan** [comment]
The `DnsServer` now accepts an `IRequestResolver` in the constructor, and `MasterFile` implements the interface. You can leave out the endpoint server now.
