### ISSUE TITLE
Unable to delete record from DNSServer or clear MasterFile?

### ISSUE THREAD

**Issue by winkmichael** [kapetan/dns#26]
Good Evening Kapetan,

Forgive, I don't believe this qualifies as an issue per se, however it is an issue for me (: Is there no way to delete a record from or clear the Masterfile?

Thank you for your hard work on the proejct and help with my issue!

**Comment by kapetan** [comment]
There is no way at the moment.

**Comment by winkmichael** [comment]
Thank you for the prompt reply, I guess my follow up question is there a way to destroy and regenerate the Masterfile? 

Thanks again

**Comment by kapetan** [comment]
No, not at the moment. I'm thinking of implementing something like suggested in https://github.com/kapetan/dns/issues/12. That should give more flexibility.

**Comment by kapetan** [comment]
The `DnsServer` now accepts an `IRequestResolver` in the constructor, and `MasterFile` implements the interface. You can provide you own implementation to the server.
