### ISSUE TITLE
NetStandard<2.0

### ISSUE THREAD

**Issue by deinok** [kapetan/dns#33]
Cant the library be compat with NetStandard 1.X?

**Comment by kapetan** [comment]
Version 2 worked with NetStandard 1.5. I have only tested version 3 with NetStandard 2.0.

**Comment by deinok** [comment]
So, can you add the netsatandard1.X or are you using a API only for netstandard2?

**Comment by kapetan** [comment]
I really don't have the time to maintain and test in different versions. I'm not planing on supporting older NetStandard versions.

**Comment by deinok** [comment]
@kapetan How would you see a fork of this library?

**Comment by kapetan** [comment]
You are more than welcome to create a fork.

**Comment by deinok** [comment]
Thanks @kapetan
