### ISSUE TITLE
Feature Request -> response.AnswerRecords[0].IPAddress

### ISSUE THREAD

**Issue by latenightbuddha** [kapetan/dns#38]
Not a bug, This might be something that was overlooked or unimplemented.
IResourceRecord in IResponse.AnswerRecords is missing IPAddress.

example: 
response.AnswerRecords[0].IPAddress

**Comment by danieljoos** [comment]
I think you need to cast it to `IPAddressResourceRecord` as shown in the example on the frontpage:
```
// Get all the IPs for the foo.com domain
IList<IPAddress> ips = response.AnswerRecords
	.Where(r => r.Type == RecordType.AAAA)
	.Cast<IPAddressResourceRecord>()
	.Select(r => r.IPAddress)
	.ToList();
```
Not all DNS requests are used to resolve IP addresses. You can also request for other types of records, like TXTs or CNAMEs

**Comment by kapetan** [comment]
@danieljoos is right, you need to cast the record first.

**Comment by latenightbuddha** [comment]
Hmm, I was unable to get that to work :/ but thanks anyway
