### ISSUE TITLE
DnsClient Lookup() causing System.OperationCanceledException'

### ISSUE THREAD

**Issue by Arunothia** [kapetan/dns#40]
The following is my code - 

```
DnsClient client = new DnsClient(PrimeDns.Config.DnsResolver_1);
ClientRequest request = client.Create();

try
 {
                mapRow.IpAddressList = await client.Lookup(pDomain);
                Console.WriteLine(mapRow.GetStringOfIpAddressList());
                mapRow.LastCheckedTime = DateTime.Now;
                mapRow.LastUpdatedTime = DateTime.Now;
                PrimeDns.Log._LogInformation("Dns Resolved successfully for Domain - " + pDomain, Logger.Logger.CDnsResolver, null);
}
 catch(Exception e)
 {
                PrimeDns.Log._LogError("Error occured while Dns resolution of Domain - " + pDomain, Logger.Logger.CDnsResolver, e);
 }
```

It is giving raise to System.OperationCanceledException.

**Comment by kapetan** [comment]
That might happen if the request times out. The default timeout is 5 seconds, maybe the dns server is not reachable.

**Comment by Arunothia** [comment]
Thanks for the reply! It was happening because of using my Office internet which was blocking out port 53.

**Comment by kapetan** [comment]
You can create an instance of `UdpRequestResolver` which takes a timeout in the constructor, and pass that to the `DnsClient`.
https://github.com/kapetan/dns/blob/c97810a5de0af1a0e589883c5b90a3a6587674ab/DNS/Client/RequestResolver/UdpRequestResolver.cs#L14
