### ISSUE TITLE
How to set to listen on specific IP Address with Local Request Resolver

### ISSUE THREAD

**Issue by lidenn** [kapetan/dns#42]
I have set up the LocalRequestResolver similar to the demo. How do I create the DNS server to listen to a specific IP Address instead of ANY with the Local Request Resolver?

**Comment by kapetan** [comment]
At the moment it's not possible. It's hard-coded here https://github.com/kapetan/dns/blob/4cf8948a9b17ab777d0996c754904172fcf2358c/DNS/Server/DnsServer.cs#L59

**Comment by kapetan** [comment]
This is now possible in version 4.1.0, as a second argument to the listen method.
