### ISSUE TITLE
How to get Requested Client IP Address?

### ISSUE THREAD

**Issue by porya0ras** [kapetan/dns#43]
I'm going to set up a geoLocation service using the DNS you have developed. so that I need to get the IP address of the requesting user. please kindly help me how to do so.

**Comment by kapetan** [comment]
This is now possible in version 5.0.0. The events now conform to the usual .NET way of emitting events, where each handler receives an sender object as first argument and event instance as second. The event instance has a `Remote` property exposing the remote IP address.
