### ISSUE TITLE
Getting Socket error

### ISSUE THREAD

**Issue by dporunne** [kapetan/dns#47]
Hi,
I keep getting the below error on running >ServerExample.exe foo.com google.com
Redirecting foo.com to localhost
Redirecting google.com to localhost
Errored: System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.UdpClient..ctor(IPEndPoint localEP)
   at DNS.Server.DnsServer.<Listen>d__26.MoveNext()

Can you tell me why I am getting this error?

**Comment by dporunne** [comment]
Following are the powershell commands that I ran:

PS F:\> Get-NetTCPConnection -LocalPort 53

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting OwningProcess
------------                        --------- -------------                       ---------- -----       -------------- -------------
172.168.111.1                       53        0.0.0.0                             0          Listen                     14304
172.18.224.1                        53        0.0.0.0                             0          Listen                     14304


PS F:\> Get-Process -Id 14304

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    296      19    22072      34244             14304   0 dockerd

**Comment by bonesoul** [comment]
can you post the code you use?

**Comment by priestofpsi** [comment]
I had the same issue...

Turns on my PC was automatically starting the "Internet Connection Sharing" (ICS) windows service, which hosts it's own DNS server to doing the pass through requests.

I disabled the Internet Connection Sharing windows service, and the Server started up without issue.

**Comment by kapetan** [comment]
This seems to be caused by a socket already listening on port 53.
