### ISSUE TITLE
SRV Record Support.

### ISSUE THREAD

**Issue by Myvar** [kapetan/dns#53]
Please add support for SRV Record.

_Originally posted by @AlexLaroche in https://github.com/kapetan/dns/issues/22#issuecomment-458385338_

I need this support as well, i don't mind implementing it my self, would you mind just giving me a brief description on how to do this, or any docs on dns that i might need, then il fork the project and make pr once i get it working ?

**Comment by danieljoos** [comment]
The implementation can be done by adding a new `SrvResourceRecord` (or so) class in the `/DNS/Protocol/ResourceRecords` folder.
You can have a look at other kinds of records there, e.g. the IP Address RR, here:
https://github.com/kapetan/dns/blob/master/DNS/Protocol/ResourceRecords/IPAddressResourceRecord.cs

Those classes basically have two constructors:
1. One that takes the base `ResourceRecord` object. This is used when the client parses records.
2. Another one that is used for the DNS server use-case, where you want to construct a RR that is provided via your server.

The wiring of those classes to the actual RR type is done in the `ResourceRecordFactory`:
https://github.com/kapetan/dns/blob/master/DNS/Protocol/ResourceRecords/ResourceRecordFactory.cs

The SRV Resource Records are described in RFC2782:
https://www.ietf.org/rfc/rfc2782.txt

**Comment by MyvarHD** [comment]
Il take a crack at it.

**Comment by MyvarHD** [comment]
#54 Done.

In my mind i imagined this taking hours but it was actually not that bad.

**Comment by kapetan** [comment]
Added SRV record implementation https://github.com/kapetan/dns/commit/7673e950ca82cf88b10d68121ff3d1433e25eff9
