### ISSUE TITLE
server sample dont work in browser

### ISSUE THREAD

**Issue by furesoft** [kapetan/dns#6]
hi, ive tried to redirect my own name record to googles ip.

but the browser dont accept it and googles the name record.

how can i fix it?

thanks

**Comment by kapetan** [comment]
Can you post your code?

**Comment by furesoft** [comment]
it is the sample code

**Comment by kapetan** [comment]
ServerExample.com google.com

The above works fine for me. Make sure the browser URL is exactly `http://google.com`. Else try addtionally passing `*.google.com` to the command.

**Comment by furesoft** [comment]
i and a friend get website not available, ive tracked the domain furesoft.gerabronn to facebook for example.

ive tried both versions and with original source, doesnt work
