### ISSUE TITLE
IPv6 problem

### ISSUE THREAD

**Issue by HTD** [kapetan/dns#64]
Here's my code fragment:

```
var networkInterface = NetworkInterface
    .GetAllNetworkInterfaces()?
    .FirstOrDefault(i => i.OperationalStatus == OperationalStatus.Up && i.NetworkInterfaceType != NetworkInterfaceType.Loopback);
if (networkInterface is null) return;
var dns = networkInterface
    .GetIPProperties()
    .DnsAddresses
    .FirstOrDefault(i => i.AddressFamily == AddressFamily.InterNetwork)
    ?? new IPAddress(new byte[] { 8, 8, 8, 8 });
Client = new DnsClient(dns);
```
I had to filter my network interface addresses to IPv4 only, because I got following exception on lookup:

> An address incompatible with the requested protocol was used

Stack trace:

>    at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult)
>    at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state)
>    at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
>    at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, IPEndPoint endPoint)
>    at DNS.Client.RequestResolver.UdpRequestResolver.<Resolve>d__5.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at DNS.Client.ClientRequest.<Resolve>d__24.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at DNS.Client.DnsClient.<Lookup>d__9.MoveNext()

**Comment by kapetan** [comment]
Should be fixed by https://github.com/kapetan/dns/commit/c80791f2cf128c775823ed13e72781ed5f629680
