### ISSUE TITLE
Question for reverse lookup (PTR)

### ISSUE THREAD

**Issue by WattsC-90** [kapetan/dns#65]
How can I create a question for the requester for a reverse lookup? I cannot see how I can pass any argument(s) into the question for it to use for a PTR request?

``` c#
ClientRequest request = new ClientRequest("192.168.4.0");

request.Questions.Add(new Question(Domain.FromString("192.168.4.1"), RecordType.PTR, RecordClass.ANY));
	
request.RecursionDesired = true;

ClientResponse response = (ClientResponse)await request.Resolve();
```

**Comment by kapetan** [comment]
You can see how reverse lookup is implemented in the [DnsClient](https://github.com/kapetan/dns/blob/90793eff73bc87b49262234da516fac72aea3efb/DNS/Client/DnsClient.cs#L63-L72). Use `Domain.PointerName` to get a correctly formatted `Domain` for reverse lookup.
