### ISSUE TITLE
Getting it working in .NET 3.5

### ISSUE THREAD

**Issue by greggman** [kapetan/dns#9]
I'm not a .NET guru at all so rather than browser the code I just thought I'd ask for direction. 

If I wanted to try to get this to work in .NET 3.5 (or rather Unity3D) can you point me in the direction of the things I'd have to take a look at and what you think might be entailed? 

Thank you

**Comment by kapetan** [comment]
Sorry it took so long time to answer. I only tested this in .NET 4, and don't know which parts are not available in 3.5.

If you tried to compile the code in 3.5, I would be interested in hearing the result, if you got it working or the error the compiler produced.

**Comment by greggman** [comment]
So I've finally started looking into this. AFAIK the only .NET 4 thing needed is `BlockingCollection`. I'm probably just missing something but it seems like just a few lines of code to write my own. We'll see how it goes.

**Comment by greggman** [comment]
So these changes *seem* to get it to work in .NET 3.5. My cross threading fu is weak so I'm not 100% sure my BlockingCollection replacement is correct

https://github.com/kapetan/dns/compare/master...greggman:dotnet-3-5

Sorry I didn't follow the same coding style (copy and paste from some other code of mine). If you want me to make a PR I'm happy to go fix up the style to match

**Comment by kapetan** [comment]
The newest version (2.0.0) now targets .NET Standard 1.5 with async methods. I've no plans on supporting older platforms. You're always welcome to maintain your own fork of the project.
